/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaderepartos;
import java.awt.Dimension;
import sistemaderepartos.consultaPiloto;
import sistemaderepartos.consultaRepartidor;
import sistemaderepartos.consultaEnBodega;
import sistemaderepartos.consultaEnCamiones;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author dairy
 */
public class consultas extends javax.swing.JFrame {

    /**
     * Creates new form consultas
     */
    
    FondoPanel fondoso = new FondoPanel();
    public consultas() {
        this.setContentPane(fondoso);
        initComponents();
        
        this.setSize(new Dimension(500, 475));
        
        ImageIcon imagen = new ImageIcon("src/imagenes/empleados.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(img_pilotos.getWidth(), img_pilotos.getHeight(), Image.SCALE_DEFAULT));
        img_pilotos.setIcon(icono);
        this.repaint();
        
        ImageIcon imagen1 = new ImageIcon("src/imagenes/cliente.png");
        Icon icono1 = new ImageIcon(imagen1.getImage().getScaledInstance(img_repartidores.getWidth(), img_repartidores.getHeight(), Image.SCALE_DEFAULT));
        img_repartidores.setIcon(icono1);
        this.repaint();
        
        ImageIcon imagen2 = new ImageIcon("src/imagenes/bodega.png");
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(img_bodega.getWidth(), img_bodega.getHeight(), Image.SCALE_DEFAULT));
        img_bodega.setIcon(icono2);
        this.repaint();
        
        ImageIcon imagen3 = new ImageIcon("src/imagenes/camion.png");
        Icon icono3 = new ImageIcon(imagen3.getImage().getScaledInstance(img_camion.getWidth(), img_camion.getHeight(), Image.SCALE_DEFAULT));
        img_camion.setIcon(icono3);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        lbl_empleados = new javax.swing.JLabel();
        img_pilotos = new javax.swing.JButton();
        lbl_vehiculo = new javax.swing.JLabel();
        img_camion = new javax.swing.JButton();
        img_bodega = new javax.swing.JButton();
        lbl_bodega = new javax.swing.JLabel();
        lbl_cliente = new javax.swing.JLabel();
        img_repartidores = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(624, 435));

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("CONSULTAS");

        lbl_empleados.setForeground(new java.awt.Color(255, 255, 255));
        lbl_empleados.setText("PILOTOS");

        img_pilotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        img_pilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                img_pilotosActionPerformed(evt);
            }
        });

        lbl_vehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vehiculo.setText("ENCARGADO DE CAMIONES");

        img_camion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camion.png"))); // NOI18N
        img_camion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                img_camionActionPerformed(evt);
            }
        });

        img_bodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bodega.png"))); // NOI18N
        img_bodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                img_bodegaActionPerformed(evt);
            }
        });

        lbl_bodega.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bodega.setText("ENCARGADO DE BODEGAS");

        lbl_cliente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cliente.setText("REPARTIDORES");

        img_repartidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        img_repartidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                img_repartidoresActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(img_pilotos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_empleados))
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cliente)
                                    .addComponent(img_repartidores, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_bodega)
                                    .addComponent(img_bodega, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(img_camion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_vehiculo))
                                .addGap(79, 79, 79))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_regresar)
                        .addGap(72, 72, 72)
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_regresar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_empleados)
                    .addComponent(lbl_cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_pilotos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img_repartidores, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_bodega)
                        .addGap(18, 18, 18)
                        .addComponent(img_bodega, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_vehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(img_camion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void img_pilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_pilotosActionPerformed
        consultaPiloto volver = new consultaPiloto();
        volver.setVisible(true);
        dispose();
        volver.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_img_pilotosActionPerformed

    private void img_camionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_camionActionPerformed
        consultaEnCamiones volver = new consultaEnCamiones();
        volver.setVisible(true);
        dispose();
        volver.setLocationRelativeTo(null);
    }//GEN-LAST:event_img_camionActionPerformed

    private void img_bodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_bodegaActionPerformed
        consultaEnBodega volver = new consultaEnBodega();
        volver.setVisible(true);
        dispose();
        volver.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_img_bodegaActionPerformed

    private void img_repartidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_repartidoresActionPerformed
        consultaRepartidor volver = new consultaRepartidor();
        volver.setVisible(true);
        dispose();
        volver.setLocationRelativeTo(null);
    }//GEN-LAST:event_img_repartidoresActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        menu volver = new menu();
            volver.setVisible(true);
            dispose();
             volver.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton img_bodega;
    private javax.swing.JButton img_camion;
    private javax.swing.JButton img_pilotos;
    private javax.swing.JButton img_repartidores;
    private javax.swing.JLabel lbl_bodega;
    private javax.swing.JLabel lbl_cliente;
    private javax.swing.JLabel lbl_empleados;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_vehiculo;
    // End of variables declaration//GEN-END:variables
    
    class FondoPanel extends JPanel
    {
            private Image imagen;
            
            @Override           
            public void paint(Graphics g)
            {
                imagen = new ImageIcon(getClass().getResource("/imagenes/fondo1.png")).getImage();
                
                g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
                
                setOpaque(false);
                
                super.paint(g);
            }
    }
}
